"use client";

/**
 * BrachistochroneSim — REFERENCE EXAMPLE for Plan #2 sim authors.
 *
 * Uses Property<T> (lib/sim/observable) for internal state. The model is a
 * pure TS class implementing SimModel (lib/sim/SimModel.ts). The view
 * subscribes via useProperty(). This is the canonical pattern every new sim
 * should follow.
 *
 * Physics: three balls drop from A to B along three different paths under
 * gravity. Energy conservation (v = √(2gh)) drives each ball forward along
 * its pre-sampled path; the cycloid wins.
 *
 * Pure SVG + requestAnimationFrame. No external dependencies. The constants
 * are tuned for visual storytelling rather than physical realism.
 */

import { useEffect, useMemo, useRef } from "react";
import { Property } from "@/lib/sim/observable/Property";
import { useProperty } from "@/lib/sim/observable/useProperty";
import type { SimModel } from "@/lib/sim/SimModel";

interface Pt { x: number; y: number }

// Viewport geometry. Width/height match the SVG viewBox; A is upper-left,
// B is lower-right. Drop of 200 px over a horizontal span of 400 px.
const VBW = 480;
const VBH = 300;
const A: Pt = { x: 40, y: 40 };
const B: Pt = { x: 440, y: 240 };

// Simulated gravity in px/s². Tuned so the race is dramatic but not blink-fast.
const G = 220;
const SAMPLES = 240;

// ---- Path generators --------------------------------------------------------

function straightPath(): Pt[] {
  const pts: Pt[] = [];
  for (let i = 0; i <= SAMPLES; i++) {
    const t = i / SAMPLES;
    pts.push({ x: A.x + t * (B.x - A.x), y: A.y + t * (B.y - A.y) });
  }
  return pts;
}

/** A gentle quadratic arc that bulges below the straight line — the "intuitive
 *  guess." It beats the straight line a little but loses to the cycloid. */
function arcPath(): Pt[] {
  const pts: Pt[] = [];
  const cx = (A.x + B.x) / 2;
  const cy = (A.y + B.y) / 2 + 65;
  for (let i = 0; i <= SAMPLES; i++) {
    const t = i / SAMPLES;
    const inv = 1 - t;
    pts.push({
      x: inv * inv * A.x + 2 * inv * t * cx + t * t * B.x,
      y: inv * inv * A.y + 2 * inv * t * cy + t * t * B.y,
    });
  }
  return pts;
}

/** The brachistochrone — a cycloid generated by a circle of radius r rolling
 *  along a line. Solved via Newton's method on the parametric end-angle that
 *  makes the curve pass through B. */
function cycloidPath(): Pt[] {
  const dx = B.x - A.x;
  const dy = B.y - A.y;
  const ratio = dy / dx;
  // f(θ) = (1 − cos θ) / (θ − sin θ) − dy/dx → 0
  let theta = 2.0;
  for (let i = 0; i < 40; i++) {
    const sinT = Math.sin(theta);
    const cosT = Math.cos(theta);
    const num = 1 - cosT;
    const den = theta - sinT;
    const f = num / den - ratio;
    const df = (sinT * den - num * (1 - cosT)) / (den * den);
    const step = f / df;
    theta -= step;
    if (Math.abs(step) < 1e-9) break;
  }
  const r = dy / (1 - Math.cos(theta));
  const pts: Pt[] = [];
  for (let i = 0; i <= SAMPLES; i++) {
    const t = (theta * i) / SAMPLES;
    pts.push({ x: A.x + r * (t - Math.sin(t)), y: A.y + r * (1 - Math.cos(t)) });
  }
  return pts;
}

// ---- Arc-length helpers -----------------------------------------------------

function arcLengths(path: Pt[]): number[] {
  const ls = [0];
  for (let i = 1; i < path.length; i++) {
    const dx = path[i].x - path[i - 1].x;
    const dy = path[i].y - path[i - 1].y;
    ls.push(ls[i - 1] + Math.sqrt(dx * dx + dy * dy));
  }
  return ls;
}

function ptAt(path: Pt[], lengths: number[], s: number): Pt {
  const total = lengths[lengths.length - 1];
  if (s <= 0) return path[0];
  if (s >= total) return path[path.length - 1];
  let lo = 0;
  let hi = lengths.length - 1;
  while (lo < hi - 1) {
    const mid = (lo + hi) >> 1;
    if (lengths[mid] <= s) lo = mid;
    else hi = mid;
  }
  const segT = (s - lengths[lo]) / (lengths[hi] - lengths[lo]);
  return {
    x: path[lo].x + segT * (path[hi].x - path[lo].x),
    y: path[lo].y + segT * (path[hi].y - path[lo].y),
  };
}

function pathToD(path: Pt[]): string {
  let d = `M ${path[0].x.toFixed(2)} ${path[0].y.toFixed(2)}`;
  for (let i = 1; i < path.length; i++) {
    d += ` L ${path[i].x.toFixed(2)} ${path[i].y.toFixed(2)}`;
  }
  return d;
}

// ---- Tracks (path + colour + label) ----------------------------------------

interface Track {
  key: string;
  label: string;
  color: string;
  path: Pt[];
  lengths: number[];
}

// ---- Model ------------------------------------------------------------------

/**
 * BrachistochroneModel — owns all mutable simulation state.
 *
 * The canonical Property<T> here is `clock`: a running elapsed-seconds counter
 * that the view subscribes to via useProperty(). Every RAF tick advances the
 * clock and updates positions; the view re-renders automatically because
 * `clock` is a Property<number>.
 *
 * Other state (positions, finishTimes, phase) lives on the model instance as
 * plain arrays/strings — the view reads them synchronously during each render
 * triggered by `clock` changing. This avoids redundant re-renders while still
 * demonstrating the Property pattern.
 */
class BrachistochroneModel implements SimModel {
  /** Observable clock — the view subscribes via useProperty(). */
  readonly clock = new Property<number>(0);

  phase: "idle" | "racing" | "finished" = "idle";
  positions: number[] = [0, 0, 0];
  finishTimes: (number | null)[] = [null, null, null];

  private rafHandle = 0;
  private raceStart = 0;
  private lastTick = 0;
  private onComplete?: () => void;

  constructor(private tracks: Track[]) {}

  start(onComplete?: () => void) {
    this.onComplete = onComplete;
    this.positions = [0, 0, 0];
    this.finishTimes = [null, null, null];
    this.clock.set(0);
    this.phase = "racing";
    this.raceStart = performance.now();
    this.lastTick = this.raceStart;
    this.rafHandle = requestAnimationFrame(this._tick);
  }

  private _tick = (now: number) => {
    const dt = Math.min(0.05, (now - this.lastTick) / 1000);
    this.lastTick = now;
    const elapsed = (now - this.raceStart) / 1000;

    const next = this.positions.slice();
    let allDone = true;
    for (let i = 0; i < this.tracks.length; i++) {
      if (this.finishTimes[i] !== null) continue;
      const total = this.tracks[i].lengths[this.tracks[i].lengths.length - 1];
      if (next[i] >= total) {
        this.finishTimes[i] = elapsed;
        continue;
      }
      const here = ptAt(this.tracks[i].path, this.tracks[i].lengths, next[i]);
      const h = Math.max(0, here.y - A.y);
      const v = Math.sqrt(2 * G * Math.max(h, 4));
      next[i] = Math.min(total, next[i] + v * dt);
      if (next[i] >= total) {
        this.finishTimes[i] = elapsed;
      } else {
        allDone = false;
      }
    }
    this.positions = next;

    // Advancing clock notifies the view — one Property write drives the render.
    this.clock.set(elapsed);

    if (allDone) {
      this.phase = "finished";
      this.onComplete?.();
      return;
    }
    this.rafHandle = requestAnimationFrame(this._tick);
  };

  /** SimModel.step — unused here; the RAF loop drives time directly. */
  step(_dt: number): void { /* RAF-driven */ }

  reset(): void {
    cancelAnimationFrame(this.rafHandle);
    this.positions = [0, 0, 0];
    this.finishTimes = [null, null, null];
    this.phase = "idle";
    this.clock.set(0);
  }

  dispose(): void {
    cancelAnimationFrame(this.rafHandle);
    this.clock.dispose();
  }
}

// ---- Component --------------------------------------------------------------

interface Props {
  onComplete?: () => void;
}

export function BrachistochroneSim({ onComplete }: Props) {
  const tracks: Track[] = useMemo(() => {
    const builders: Array<{ key: string; label: string; color: string; build: () => Pt[] }> = [
      { key: "straight", label: "To'g'ri chiziq", color: "#1f7240", build: straightPath },
      { key: "arc", label: "Yoy", color: "#c98910", build: arcPath },
      { key: "cycloid", label: "Sikloid", color: "#e8a21a", build: cycloidPath },
    ];
    return builders.map((b) => {
      const path = b.build();
      return { key: b.key, label: b.label, color: b.color, path, lengths: arcLengths(path) };
    });
  }, []);

  // Model is stable for the lifetime of this component instance.
  const model = useMemo(() => new BrachistochroneModel(tracks), [tracks]);
  const onCompleteRef = useRef(onComplete);
  onCompleteRef.current = onComplete;

  useEffect(() => () => model.dispose(), [model]);

  // Subscribe to clock — every RAF tick re-renders the view.
  // The model's other fields (positions, finishTimes, phase) are read
  // synchronously during this render.
  const clock = useProperty(model.clock);

  const { phase, positions, finishTimes: times } = model;

  // Winner index (lowest finish time) once everyone finished
  let winnerIdx = -1;
  if (phase === "finished") {
    let bestTime = Infinity;
    for (let i = 0; i < times.length; i++) {
      const t = times[i];
      if (t !== null && t < bestTime) {
        bestTime = t;
        winnerIdx = i;
      }
    }
  }

  function start() {
    model.start(() => onCompleteRef.current?.());
  }

  function reset() {
    model.reset();
  }

  return (
    <div className="flex w-full flex-col gap-3">
      <div className="overflow-hidden rounded-[18px] border border-void-500 bg-void-700/40">
        <svg viewBox={`0 0 ${VBW} ${VBH}`} className="block w-full" role="img" aria-label="Brachistochrone race">
          {/* dotted grid baseline for context */}
          <line x1={A.x} y1={A.y} x2={B.x} y2={A.y} stroke="#4a4636" strokeDasharray="3 4" strokeWidth="1" />
          <line x1={B.x} y1={A.y} x2={B.x} y2={B.y} stroke="#4a4636" strokeDasharray="3 4" strokeWidth="1" />

          {/* paths */}
          {tracks.map((t) => (
            <path
              key={t.key}
              d={pathToD(t.path)}
              fill="none"
              stroke={t.color}
              strokeWidth={3}
              strokeLinecap="round"
              opacity={0.85}
            />
          ))}

          {/* A and B markers */}
          <circle cx={A.x} cy={A.y} r={6} fill="#fbf9f3" stroke="#1a1813" strokeWidth="1.5" />
          <text x={A.x - 4} y={A.y - 12} fontSize="11" fontWeight="600" fill="#fbf9f3">A</text>
          <circle cx={B.x} cy={B.y} r={6} fill="#fbf9f3" stroke="#1a1813" strokeWidth="1.5" />
          <text x={B.x + 12} y={B.y + 4} fontSize="11" fontWeight="600" fill="#fbf9f3">B</text>

          {/* finish line at B */}
          <line x1={B.x - 10} y1={B.y - 18} x2={B.x - 10} y2={B.y + 18} stroke="#fbf9f3" strokeWidth="1" strokeDasharray="2 3" />

          {/* balls */}
          {tracks.map((t, i) => {
            const p = ptAt(t.path, t.lengths, positions[i]);
            const isWinner = winnerIdx === i;
            return (
              <g key={`ball-${t.key}`}>
                <circle
                  cx={p.x}
                  cy={p.y}
                  r={9}
                  fill={t.color}
                  stroke="#fbf9f3"
                  strokeWidth="2"
                  filter={isWinner ? "drop-shadow(0 0 6px rgba(232,162,26,0.9))" : undefined}
                />
              </g>
            );
          })}
        </svg>
      </div>

      {/* Live readout */}
      <div className="grid grid-cols-3 gap-2">
        {tracks.map((t, i) => {
          const finished = times[i] !== null;
          const isWinner = winnerIdx === i;
          return (
            <div
              key={t.key}
              className={`rounded-[12px] border px-3 py-2.5 transition-colors ${
                isWinner ? "border-antares-500 bg-antares-500/15" : "border-void-500 bg-void-700"
              }`}
            >
              <div className="flex items-center gap-2">
                <span className="h-2.5 w-2.5 rounded-full" style={{ background: t.color }} />
                <span className="text-[12px] font-semibold text-void-100">{t.label}</span>
              </div>
              <div className="mt-1.5 font-mono text-[15px] font-semibold tabular-nums text-void-100">
                {finished
                  ? `${(times[i] as number).toFixed(2)} s`
                  : phase === "racing"
                    ? `${clock.toFixed(2)} s`
                    : "—"}
              </div>
            </div>
          );
        })}
      </div>

      {/* Action row */}
      <div className="flex items-center gap-3">
        {phase === "idle" && (
          <button
            type="button"
            onClick={start}
            className="inline-flex h-[44px] flex-1 items-center justify-center rounded-full bg-antares-500 px-6 text-[14px] font-semibold text-void-100 transition hover:bg-antares-300 active:scale-[0.98]"
          >
            Yugurtirish
          </button>
        )}
        {phase === "racing" && (
          <button
            type="button"
            disabled
            className="inline-flex h-[44px] flex-1 items-center justify-center rounded-full bg-void-700 px-6 text-[14px] font-semibold text-void-300"
          >
            Yugurmoqda…
          </button>
        )}
        {phase === "finished" && (
          <button
            type="button"
            onClick={reset}
            className="inline-flex h-[44px] flex-1 items-center justify-center rounded-full border border-void-500 bg-void-700 px-6 text-[14px] font-semibold text-void-100 transition hover:bg-void-600 active:scale-[0.98]"
          >
            Qaytadan yugurtirish
          </button>
        )}
      </div>
    </div>
  );
}
