// AUTO-GENERATED by scripts/sync-curriculum-subjects.ts on 2026-05-23T07:27:30.527Z.
// Source: emaktab snapshot for student "demo-student-1" (Grade 6).
// DO NOT EDIT BY HAND — regenerate after each `extract-emaktab.ts`.

/** A single subject the student takes, as seen on emaktab. */
export interface EmaktabSubjectRef {
  /** Stable kebab-case id (see lib/emaktab/normalize.ts). */
  id: string;
  /** Canonical display label, e.g. "Ona tili". */
  label: string;
}

export const emaktabSubjects: EmaktabSubjectRef[] = [
  { id: "adabiyot", label: "Adabiyot" },
  { id: "informatika", label: "Informatika" },
  { id: "ingliz-tili", label: "Ingliz tili" },
  { id: "jismoniy-tarbiya", label: "Jismoniy tarbiya" },
  { id: "kelajak-soati", label: "Kelajak soati" },
  { id: "math", label: "Matematika" },
  { id: "musiqa", label: "Musiqa" },
  { id: "ona-tili", label: "Ona tili" },
  { id: "rus-tili", label: "Rus tili" },
  { id: "tabiiy-fan", label: "Tabiiy fan" },
  { id: "tarbiya", label: "Tarbiya" },
  { id: "history", label: "Tarix" },
  { id: "tasviriy-sanat", label: "Tasviriy san'at" },
  { id: "texnologiya", label: "Texnologiya" },
];
