import { writeFileSync, mkdirSync } from "fs";
import { dirname } from "path";
import { getEmaktabSubjects } from "../lib/emaktab";

/**
 * Codegen: reads the emaktab snapshot and writes the canonical subject list to
 * `lib/curriculum/subjects.generated.ts`. The generated file is committed so
 * Vercel builds (which don't have data/emaktab-export.json) can still import
 * the subject set; the curriculum graph layers curated units on top.
 *
 * Run after every `extract-emaktab.ts`:
 *   npx tsx --env-file=.env.local scripts/sync-curriculum-subjects.ts
 */

const OUT = "lib/curriculum/subjects.generated.ts";

const subjects = getEmaktabSubjects();
if (subjects.length === 0) {
  console.error("no subjects in snapshot — nothing to write");
  process.exit(1);
}

const lines = subjects
  .map((s) => `  { id: ${JSON.stringify(s.subjectId)}, label: ${JSON.stringify(s.subject)} },`)
  .join("\n");

const body = `// AUTO-GENERATED by scripts/sync-curriculum-subjects.ts on ${new Date().toISOString()}.
// Source: emaktab snapshot for student "demo-student-1" (Grade ${6}).
// DO NOT EDIT BY HAND — regenerate after each \`extract-emaktab.ts\`.

/** A single subject the student takes, as seen on emaktab. */
export interface EmaktabSubjectRef {
  /** Stable kebab-case id (see lib/emaktab/normalize.ts). */
  id: string;
  /** Canonical display label, e.g. "Ona tili". */
  label: string;
}

export const emaktabSubjects: EmaktabSubjectRef[] = [
${lines}
];
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body, "utf8");
console.log(`wrote ${OUT} — ${subjects.length} subjects`);
for (const s of subjects) console.log(`  · ${s.subjectId.padEnd(20)} ${s.subject}`);
